name: Test Build

on: [push, pull_request]

jobs:

  Test:
    runs-on: ubuntu-latest

    steps:
    - name: clone repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: yarn

    - name: Running Test
      run: yarn test
